version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-gatsby
    tty: true
    volumes:
      - ./ssh:/home/node/.ssh
      - ./app:/home/node/app
    ports:
      - "8000:8000"
      - "9000:9000"

